### ISSUE TITLE
Model Size Output from model.describe()

### ISSUE THREAD

**Issue by patrickjedlicka** [google/yggdrasil-decision-forests#146]
Hi, 

in the Serving in C++ example (https://ydf.readthedocs.io/en/stable/tutorial/cpp/#serving-in-c) you can see in the output of model.describe() the Model size of 29kB. Where is this value coming from? I don´t get this output when I run this code. 

Since the URL in the ds_path is no longer active I downloaded the iris.csv manually. 

Best regards!

**Comment by rstz** [comment]
Hi,

The model size reported by `model.describe()` is a (somewhat loose) estimate of the model's size in memory. The size of the serialized model might differ from it, mainly since protos may be stored in a more compressed format. In other words, it is probably unwise to rely on the exact value of `model.size()` for the same reasons as for [proto messages](https://github.com/protocolbuffers/protobuf/blob/63139cb1969cbd87664136814757b96a79cd8847/src/google/protobuf/message.h#L315-L317)

The model size is currently only shown in the HTML output of `model.describe()`. HTML output is the default when running in an IPython environment. You can force HTML output with `model.describe(output_format="notebook")`.

I believe the text output should also display this information and I'll make a change for the next version to add model size to the text output. 

The url in the tutorial https://raw.githubusercontent.com/google/yggdrasil-decision-forests/main/yggdrasil_decision_forests/test_data/dataset/iris.csv works fine for me, can you confirm that it does not load?

**Comment by patrickjedlicka** [comment]
Hi, thank you for the fast answer!

The link works also fine for me. I missed the "/iris.csv"...
