### ISSUE TITLE
Go model serving does not support DISCRETIZED_NUMERICAL

### ISSUE THREAD

**Issue by jimidle** [google/yggdrasil-decision-forests#55]
Using a column guide of:

```proto

column_guides {
  type: DISCRETIZED_NUMERICAL
  column_name_pattern: "^dialtimebin$"
}
```

Results in the go code issuing:

```
Error: Non supported feature dialtimebin with type DISCRETIZED_NUMERICAL
```

Is there a chance that this feature type will be supported from Go?

This field is a an hourly time bin 0-23   - is that the correct feature type to use?

**Comment by jimidle** [comment]
Hmm, wel in fact go only supports:

```go
	switch column.GetType() {

		case dataspec_pb.ColumnType_NUMERICAL:
                  // ...

		case dataspec_pb.ColumnType_CATEGORICAL:
                // ...

		default:
			return nil, nil, fmt.Errorf("Non supported feature %v with type %v",
				column.GetName(), column.GetType())
	}
```

Which means it is not so usable. Is the go runtime still supported?

**Comment by rstz** [comment]
The Go runtime is still supported, but does not offer all the features of core YDF. 

DISCRETIZED_NUMERICAL is not a feature type most people need on a regular basis.

Context: A feature of type NUMERICAL can take any (float32) value. This means that, during training, YDF examines all unique values of the feature as possible splits and computes a score for them (details and special cases omitted). This can be really slow if you have many examples and many feature values. One way to speed up training, sometimes drastically, is to pre-process a numerical feature by discretizing its values into bins, e.g., `(-inf, 0], [0,1], [1,2], [2, inf)`. Doing so often worsens model quality (but not always, since discretization also acts as regularization), so this is a trade-off to be made in the modelling phase. With type DISCRETIZED_NUMERICAL, this YDF can perform this preprocessing for you according to the data spec. See [the definition of a DISCRETIZED_NUMERICAL feature in the data spec proto message](https://github.com/google/yggdrasil-decision-forests/blob/main/yggdrasil_decision_forests/dataset/data_spec.proto#L184). 

If you need this preprocessing in Go, you'll probably need to implement the discretization outside of YDF yourself - doing so shouldn't be hard and give essentially you the same results. If you just have 24 hourly values, just use type `NUMERICAL`.

**Comment by jimidle** [comment]
Thank you for the insight - I had more or less come to the conclusion that hourly time bins are better as `NUMERICAL` but intended to switch to just categorical with a vocab size of 24. I already process the values into `[0,23]` anyway. I agree that this case does not seem to fit `DISCRETIZED_NUMERICAL`.

**Comment by rstz** [comment]
Hi, good to hear - indeed, `CATEGORICAL` might also be a good choice depending on the semantic you have.
